### ISSUE TITLE
Plot function: clean up

### ISSUE THREAD

**Issue by miggland** [SPLIfA/CAT#81]
In the plotting function, figure handles should not be predefined, as this may interfere with other plots which the user has opened.
The plot function should return the figure handles on request, along with the handles to the created plot objects (lines, surfaces).
Calling plot again should not recreate the figures, but use the existing ones

I imagine something like this in the plotting function:

1. Check the children vector - if its empty, create all the figures, new plots. Return/save figure handles to children property
2. If children are defined, do not open ANY new figures by default (unless plotwhat is defined). Plot current values into existing figure

For this to work, the number of figures and the order of the figure handles has to be defined. Alternatively, one could define figure titles and check these for the existing figure handles.

**Comment by bizzinho** [comment]
Looks fine to me. Additional behavior: append mode (overwrite may remain default)
