### ISSUE TITLE
massmedium scalar not vector

### ISSUE THREAD

**Issue by bizzinho** [SPLIfA/CAT#97]
O.handles_objects{p} = [...
                        line(O.calc_time,O.calc_conc,...
                            'Color',color,'LineStyle',linestyle,'Marker',markerstyle,...
                            'Parent',axh(1)),...
                        line(O.calc_time,O.calc_conc./evalanonfunc(O.solubility,evalanonfunc(O.Tprofile,O.calc_time),evalanonfunc(O.ASprofile,O.calc_time)./O.massmedium),...
                            'Color',color,'LineStyle',linestyle,'Marker',markerstyle,...
                            'Parent',axh(2)),...
                        line(O.calc_time,Tprof,...
                            'Color',color,'LineStyle',linestyle,'Marker',markerstyle,...
                            'Parent',axh(3))...
                        line(O.calc_time,O.massmedium,...
                            'Color',color,'LineStyle',linestyle,'Marker',markerstyle,...
                            'Parent',axh(4))...
                        ];

this can result in an issue when massmedium does not change -> remains scalar, code tries to plot(vector,scalar), returns vector of handles, stacking then fails on this line.

**Comment by miggland** [comment]
Best solution may be to force massmedium into a vector always (in
solver) 

Alternative, for plotting, add the following before the quoted code: 

if isscalar(O.massmedium) 

p_massmedium = O.massmedium*ones(size(O.calc_time)); 

else 

p_massmedium = O.massmedium; 

end % if else 

and, change O.massmedium to p_massmedium in the last line(... command
quoted 

On 2015-07-14 16:52, Dave Ochsenbein wrote: 

> O.handles_objects{p} = [...
> line(O.calc_time,O.calc_conc,...
> 'Color',color,'LineStyle',linestyle,'Marker',markerstyle,...
> 'Parent',axh(1)),...
> line(O.calc_time,O.calc_conc./evalanonfunc(O.solubility,evalanonfunc(O.Tprofile,O.calc_time),evalanonfunc(O.ASprofile,O.calc_time)./O.massmedium),...
> 'Color',color,'LineStyle',linestyle,'Marker',markerstyle,...
> 'Parent',axh(2)),...
> line(O.calc_time,Tprof,...
> 'Color',color,'LineStyle',linestyle,'Marker',markerstyle,...
> 'Parent',axh(3))...
> line(O.calc_time,O.massmedium,...
> 'Color',color,'LineStyle',linestyle,'Marker',markerstyle,...
> 'Parent',axh(4))...
> ]; 
> 
> this can result in an issue when massmedium does not change -> remains scalar, code tries to plot(vector,scalar), returns vector of handles, stacking then fails on this line. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/SPLIfA/CAT/issues/97
