### ISSUE TITLE
WIKI IMages broken again

### ISSUE THREAD

**Issue by Persephone3** [SPLIfA/CAT#99]
I cannot see any of the images in the wiki. They are all appearing in my browser as broken links. I tried IE and also Chrome.

**Comment by bizzinho** [comment]
Thx for letting us know and sorry for the delay. We'll look into it.

**Comment by bizzinho** [comment]
Figures are not in my backup files. @ash23win do you still have some backups? Schould be in a former HAL folder called "CATWIKI", probably in var/www

**Comment by numb90** [comment]
Hi guys, this issue still exists. Can you do something about it? I would really like to see the document with formulas available. Thanks.

**Comment by bizzinho** [comment]
This is a known issue. Unfortunately, back when the servers were wiped, no backup of the images was created. At this point it seems unlikely that the ETH team has the time or resources to recreate them.
